lib/EnsEMBL/REST/Model/Lookup.pm
Consistent with the condition in the error reporting at line 229
=> Make sure long lookup happens if @captures first element is false

lib/EnsEMBL/REST/Controller/ga4gh/variants.pm, lib/EnsEMBL/REST/Model/ga4gh/variants.pm, t/gavariant.t
=> fix for paging & move checks to post method for variants

t/test-genome-DBs/testdata/ga_data/ga_vcf_config.json
Update configuration file for loading data from VCF files. Updates are related to the variation schema changes for release 81.
=> Update individual to sample to match schema changes in release 81

lib/EnsEMBL/REST/Model/Variation.pm, lib/EnsEMBL/REST/Model/ga4gh/callSet.pm, lib/EnsEMBL/REST/Model/ga4gh/variants.pm, t/variation.t
plus minor allele addition to variation endpoint
=> GA4GH endpoints updated after sample schema change

lib/EnsEMBL/REST/Controller/GeneTree.pm, lib/EnsEMBL/REST/Role/Tree.pm, lib/EnsEMBL/REST/View/OrthoXML.pm, root/documentation/compara.conf, t/lib/RestHelper.pm
I have basically copied all the PhyloXML bits and renamed to OrthoXML.
Tested on farm3
=> Support OrthoXML output for gene trees

.travis.yml, Makefile.PL, cpanfile
which is basically a copy of Makefile.PL, but it simplifies setting-up a REST server on the user side and in other teams' test-suites
=> Added a cpanfile

lib/EnsEMBL/REST/Controller/VEP.pm
SV types were having an allele string constructed for them, which mean they weren't getting parsed into StructuralVariationFeatures as intended.
This also meant time was wasted looking up sequence.
=> dont construct allele string for SV types

root/documentation/vep.conf
These are the plugins I intend to have live this release.
I'll create a PR to the private repo with the configs
=> add doc elements for VEP plugins

root/documentation/ld.conf
=> Improve spelling of parameter names in documentation

root/documentation/overlap.conf
Improve overlap documentation as per Simon's suggestion.
=> add variant set list

lib/Plack/Middleware/EnsThrottle.pm, t/ratelimit.t
Rate limit override headers to disable 429 return code
Tests to demonstrate the override works
=> Enscoresw 1551

root/documentation/sequence.conf
- Documentation for start/end parameters not added to documentation in original push.
=> Jira ENSCORESW-1480

lib/EnsEMBL/REST/Controller/Homology.pm
In short:
- the Compara API is able to filter the target species
- a few things could be rewritten in a clearer way
=> Several improvements for the Homology endpoints

ensembl_rest.conf.default, lib/EnsEMBL/REST/Controller/GeneTree.pm, root/documentation/compara.conf
In short:
- added options to prune the gene-trees (like on the homology side)
- added more examples
=> Several improvements to the Gene-tree endpoints

lib/EnsEMBL/REST/Model/LDFeatureContainer.pm, root/documentation/ld.conf, t/ld.t
We have worked on speed improvements for the LD calculation this release. We can now increase the window_size for the LD REST endpoint and make the window_size parameter customisable. Max allowed value is 1MB.
=> Feature 84/ld increase window

lib/EnsEMBL/REST/Controller/LD.pm, lib/EnsEMBL/REST/Model/LDFeatureContainer.pm, root/documentation/ld.conf, t/ld.t
Add new LD endpoint. Compute LD values for a specified region.
=> Feature 84/new ld endpoints

lib/EnsEMBL/REST/Model/Lookup.pm
s/Include/Expand/ when expand parameter is given but not allowed
=> Fixed error message

t/transcript_haplotypes.t
This along with fix in ensembl-variation should fix broken test suite
=> add records for implicit _all population to transcript haplotype output

lib/EnsEMBL/REST/Controller/Variation.pm, lib/EnsEMBL/REST/Model/Variation.pm
Might solve your slow ID request problem.
But then again it might not.
It should at least be faster.
=> use fetch_all_by_name_list instead of single fetches

lib/EnsEMBL/REST/Controller/Variation.pm, lib/EnsEMBL/REST/Model/LDFeatureContainer.pm, lib/EnsEMBL/REST/Model/Variation.pm
Return more variant attributes in the LD endpoint.
=> At7 master/ld add more data

lib/EnsEMBL/REST/Model/ga4gh/variantSet.pm, lib/EnsEMBL/REST/Model/ga4gh/variants.pm
Creates the default ensembl version variant set needed by variant annotations
=> fix for annotation variant set

root/documentation/gavariantannotation.conf
=> neaten variantAnnotation docs

t/overlap.t
VariationFeature summary as hash has been updated to supply source. This updates the test.
=> update test for overlap variation source

lib/EnsEMBL/REST/Controller/Info.pm, lib/EnsEMBL/REST/Model/Registry.pm, root/documentation/info.conf, t/info.t, t/test-genome-DBs/homo_sapiens/core/meta.txt
Updates to include strain and strain_collection info in REST endpoint info/species - ENSCORESW-1964
=> Enscoresw 1964

t/gareferences.t
=> update test 

t/test-genome-DBs/homo_sapiens/funcgen/meta.txt, t/test-genome-DBs/homo_sapiens/funcgen/regulatory_build.txt, t/test-genome-DBs/homo_sapiens/funcgen/table.sql
Apply patch 'patch_87_88_c.sql' to funcgen test db
=> patch funcgen test dbs

ensembl_rest.conf.default, root/documentation/phenotypefeatures.conf
=> Use placeholder in phenotype region endpoint documentation

lib/EnsEMBL/REST/Model/Regulatory.pm
Removing deprecated message from server log
=> Changed display_id to stable_id

t/variation.t
Slight modification to the expected results for the tests from file variation.t. 
The values from the keys: Frequency + allele_count were modified to accept numeric data
=> ENSCORESW-2234

lib/EnsEMBL/REST/Controller/Variation.pm, lib/EnsEMBL/REST/Model/Variation.pm, root/documentation/variation.conf, t/variation.t
2 configuration options to be added, variation_pmid, variation_pmcid
=> Endpoint to retrieve variant records by publication

lib/EnsEMBL/REST/Controller/VEP.pm
To resolve "Missing reference or alternate sequence" issue
=> set default reference allele for insertion

t/overlap.t
=> updated array_probe test

root/documentation/compara.conf
_One or more sentences describing in detail the proposed changes._
Lorem ipsum dolor sit amet, consectetur …
=>  updated compara endpoints documentation

root/wrapper.tt
New GDPR privacy policy link
Users can enjoy reading the updated policy
We may lose users if they don't accept the privacy policy
Tested successfully in sandbox
=> add new privacy policy link on top banner

t/vep.t
NA
Responding to @premanand17 suggestion to make use of json number types consistent across the vep tests. (https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-1110)
NA
Ensure consistency
NA
Done. tests pass.
NA
=> Use numbers where appropriate

lib/EnsEMBL/REST/Model/Regulatory.pm
_Describe the problem. Please provide an …
=> Adjusted method name to match name in Funcgen module

bin/production/server_control.pl
Add perl module dependencies that were missing from previous pull request (see https://github.com/Ensembl/ensembl-rest/pull/283)
Implemented and working on test.rest.ensembl.org
=> Add missing perl module dependencies

bin/production/server_control.pl
See https://github.com/Ensembl/ensembl-rest/pull/300
=>  Add missing perl module dependencies (for master) 

bin/production/server_control.pl
See https://github.com/Ensembl/ensembl-rest/pull/309
=> Only try to create log/PID dirs if the server is starting (for branch release/95)

t/test-genome-DBs/homo_sapiens/funcgen/meta.txt, t/test-genome-DBs/homo_sapiens/funcgen/regulatory_build.txt, t/test-genome-DBs/homo_sapiens/funcgen/table.sql
Apply ensembl-funcgen schema patches to test dbs
Testing
Happy Travis
None
None required
They do
Yes
=> Test schema patches for late regulation changes.

lib/EnsEMBL/REST/Model/Registry.pm
Allow starting the REST server if Registry eQTL data cannot be preloaded.
As it stands, the server fails to start if it has been configured to provide /eqtl endpoints with Registry preloading enabled (which is recommended by documentation for enabling eQTL). This means problems with the file system holding eQTL data files can keep the whole REST server down.
Nb. this only seems to be a problem when starting the server, the case of eQTL files disappearing with the server already running appear to be handled gracefully by existing code.
Unavailability of eQTL data files will no longer prevent access to non-eQTL endpoints.
The server will still have to be manually restarted when the files reappear.
No. …
=> Allow starting the REST server if Registry eQTL data cannot be preloaded

ensembl_rest.conf.default, lib/EnsEMBL/REST/Model/Registry.pm, t/info.t
Repeat of https://github.com/Ensembl/ensembl-rest/pull/323 for the master branch
=> Change default division to be 'EnsemblVertebrates' (master)

lib/EnsEMBL/REST/Controller/Info.pm, lib/EnsEMBL/REST/PreloadRegistry.pm, lib/EnsEMBL/REST/RegistryHelper.pm
A few fixes for joint REST
- Fix `info/info_genome` endpoint
- Use better format for specifying multiple db configs 
- Fix registry helper bug by removing a db disconnect left in by mistake
=> Fixes for joint REST

root/documentation/vep.conf
Add the existing Phenotypes VEP plugin as an option to the REST VEP endpoint.
This documentation is needed for the plugin to be visible on the REST endpoint page.
Users will be able to retrieve phenotypic information reported by the plugin.
None.
No tests added. Local test server page checked manually.
No change to code. Test …
=> add documentation to VEP endpoint for new plugin

lib/EnsEMBL/REST/Controller/ga4gh/Beacon.pm, lib/EnsEMBL/REST/Model/ga4gh/Beacon.pm, root/documentation/gabeacon.conf, t/gabeacon.t
There are new ga4gh Beacon specifications, the endpoints need to be updated. 
Current version is outdated, the endpoints need to be updated according to the latest specification. 
Updated endpoints 
None 
Yes, I modified a few tests and added new ones. 
They pass. 
ga4gh/beacon/query Add support to structural variants with new fields variantType and start (optional in case of sv); changed message errors display
=> Update Beacon endpoint 

cpanfile, lib/EnsEMBL/REST/Model/Documentation.pm
Add missing YAML CPAN dependency as required here https://github.com/Ensembl/ensembl-rest/blame/release/97/lib/EnsEMBL/REST/Model/Documentation.pm#L33
=> Add missing YAML CPAN dependency

lib/EnsEMBL/REST/Model/Registry.pm
=> Fix for HDF5 issue

root/documentation/vep.conf
Add documentation for the new optional SpliceRegion plugin in the VEP REST endpoint. The corresponding configuration update is PR https://github.com/Ensembl/ensembl-rest_private/pull/62
Existing plugin functionality will now be available through REST.
live: http://rest.ensembl.org/documentation/info/vep_id_get
proposed: http://hx-noah-07-02:3000/documentation/info/vep_id_get
Without this documentation, the endpoint will not display the availability of the functionality in the background.
_If applicable, describe any possible …
=> Add documentation for SpliceRegion plugin -e99

t/test-genome-DBs/homo_sapiens/variation/table.sql
Fix for failing variation.t test
Allows for travis tests to pass
_Have you added/modified unit tests to test the …
=> table.sql fix

t/test-genome-DBs/homo_sapiens/variation/table.sql
Requirements
Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion;
Review the contributing guidelines for this repository; remember in particular:
do not modify code without testing for regression
provide simple unit tests to test the changes
the PR must not fail unit testing
if you're adding/updating documentation of an endpoint, make sure you add/update the necessary parameters to the (template) configuration files in the ensembl-rest_private repo
Description
Fix for failing variation.t test
Use case
Allows for travis tests to pass
Benefits
Possible Drawbacks
Testing
Have you added/modified unit tests to test the changes?
If so, do the tests pass/fail?
Yes
Have you …
=> Table.sql update

t/test-genome-DBs/homo_sapiens/variation/meta.txt, t/test-genome-DBs/homo_sapiens/variation/table.sql
Patch variation_citation table. 
The attrib ids used in table.sql are wrong. They have to be fixed for the right values.
attrib_ids in variation_citation match attrib_id in attrib table
None 
Yes, no regression detected. 
No
=> Patch table variation_citation 

t/test-genome-DBs/homo_sapiens/funcgen/meta.txt, t/test-genome-DBs/homo_sapiens/funcgen/table.sql
Apply release 100 schema patches to the Funcgen test DB
Apply release 100 schema patches to the Funcgen test DB
Funcgen …
=> applied patches to homo_sapiens funcgen test DB

lib/EnsEMBL/REST/Model/ga4gh/Beacon.pm, t/gabeacon.t
Update Beacon endpoint: small change to the response, fix a bug and add a test.
This update is necessary to have a more precise response. 
Improve beacon response.
None, the old queries still work and the output has the same format. 
Yes. Update one test and add a new one. 
Pass
No regression detected. 
The functionality is the same.
=> Update Beacon allele response

ensembl_rest.conf.default, root/documentation/compara_grch37.conf
Refer to PR 409
NA
No change in endpoints
=> correction in variable ids used for grch37 rest documentation

t/test-genome-DBs/homo_sapiens/variation/attrib.txt, t/test-genome-DBs/homo_sapiens/variation/attrib_type.txt, t/test-genome-DBs/homo_sapiens/variation/meta.txt, t/test-genome-DBs/homo_sapiens/variation/phenotype.txt, t/test-genome-DBs/homo_sapiens/variation/table.sql
Apply e101 patch for variation test db.
Test database will be on e101 schema.
Test database will be on e101 schema.
NA
Tests are passing.
=> patch test variation db for e101

t/test-genome-DBs/homo_sapiens/funcgen/meta.txt
Applied patch to test db Funcgen release 101
Applied patch to test db Funcgen release 101
Test db will up to date
=> funcgen test db patched for rel 101

root/documentation/vep.conf
One more VEP plugin will be available through the VEP endpoint. This documentation is needed for the plugin. 
The endpoint needs documentation to be displayed. 
None, the default behavior is the same. 
The tests are failing because of branches. 
[/vep/:species/hgvs/] new plugin option added: SpliceAI
[/vep/:species/id/] new plugin option added: SpliceAI
[/vep/:species/region/] new plugin option added: SpliceAI
=> Update vep endpoint docs

lib/EnsEMBL/REST/Controller/VEP.pm, root/documentation/vep.conf
Master equivalent of #415 415
Adds shifting code to REST
Improved VEP functionality
None, it doesn't change default …
=> Shifting updates for master

lib/EnsEMBL/REST.pm
Bumps the version and updates the wiki submodule
Bumps the version in lib/EnsEMBL/REST.pm and updates the wiki submodule …
=> Bump documentation and REST API version to 13.0

root/documentation/phenotypefeatures.conf
In e101 phenotype endpoint has been extended by a few parameters. The parameter definition from 2 of them is here being updated to be clearer (the functionality was already added for e101 in PR https://github.com/Ensembl/ensembl-rest/pull/421).
Users will understand better the effect of the new parameters.
Improved clarity.
None.
Have tested visually the display of the docs.
NA
=> update parameter definition -e101

root/documentation/phenotypefeatures.conf
Same as PR https://github.com/Ensembl/ensembl-rest/pull/43 this time on master.
In e101 phenotype endpoint has been extended by a few parameters. The parameter definition from 2 of them is here being updated to be clearer (the functionality was already added for e101 in PR #421).
Users will understand better the effect of the new parameters.
Improved clarity.
None.
Have tested visually the display of the docs.
NA
=> update parameter definition -master 

cpanfile
Same as #438 but against master
=> pinned Mojolicious to 8.43

t/test-genome-DBs/homo_sapiens/funcgen/meta.txt, t/test-genome-DBs/homo_sapiens/funcgen/table.sql
Funcgen Test DB patch for e102
Apply e102 schema patches to test DB
Test DB will be up to date
Updated files have been …
=> funcgen test DB patch for e102

ensembl_rest.conf.default, root/documentation/info_grch37.conf
Same as https://github.com/Ensembl/ensembl-rest/pull/442
=> Remove some info endpoints on Grch37 release/101

ensembl_rest.conf.default, root/documentation/info_grch37.conf
Same as https://github.com/Ensembl/ensembl-rest/pull/442
=> Remove some info endpoints on Grch37 release/102

lib/EnsEMBL/REST/Model/ga4gh/Beacon.pm, t/gabeacon.t
Update the Ensembl Beacon ID
The current Beacon ID is not compatible with the Network specifications. 
To be able to register the Beacon in the Elixir Beacon Network. 
None
The test was updated. 
Test pass
No change in functionality.
=> Beacon ID update (102) 

lib/EnsEMBL/REST/Model/ga4gh/Beacon.pm, t/gabeacon.t
Update the Ensembl Beacon ID. Same as #457 
The current Beacon ID is not compatible with the Network specifications. 
To be able to register the Beacon in the Elixir Beacon Network. 
None
The test was updated. 
Test pass
No change in functionality.
=> Beacon ID update (103) 

.travis.yml
Correct branch in travis file for build
For checking out correct branch during tests in travis build
Tests running off …
=> corrected branch in .travisyml for 103

cpanfile
The same as https://github.com/Ensembl/ensembl-rest/pull/463, but to release/103
=> Add Starman to the cpanfile

t/test-genome-DBs/homo_sapiens/funcgen/meta.txt, t/test-genome-DBs/homo_sapiens/funcgen/table.sql, t/test-genome-DBs/homology/compara/meta.txt, t/test-genome-DBs/homology/compara/table.sql, t/test-genome-DBs/multi/compara/meta.txt, t/test-genome-DBs/multi/compara/table.sql
Test db updated for 103: funcgen/regulation and compara
Part of release SOP
Updated test db for the release
NA
No change …
=> 103: updated testdb for regulation and compara

README.md
Updates now that release/102 is live - wiki submodule updated to latest wiki version, and build version updated for …
=> update wiki submodule and badge branches

t/test-genome-DBs/homo_sapiens/funcgen/meta.txt
Patch for release 104 for funcgen test  db
Patch for release 104 for funcgen test  db
--
--
--
--
=> funcgen test db patch

lib/EnsEMBL/REST/Model/Regulatory.pm
Update deprecated methods in Regulatory module
Some methods have been renamed
Rest end point will work as expected
=> Update Deprecated Methods

lib/EnsEMBL/REST.pm
Updated docs to point to new change-log (with version 15.0). This needs to be pushed to master before branching to release/105
=> Doc updated for release 105

.travis.yml, README.md
Fixed README and .travis.yml
N/A
N/A
N/A
N/A
N/A
=> Fix README and .travis.yml

lib/EnsEMBL/REST.pm
N/A
Updating doc for including changes for SpliceAI endpoints, as per PR #501 
N/A
Updated documentation and related version
N/A
N/A
N/A
=> Doc updated for SpliceAI plugin endpoints for release 106

t/test-genome-DBs/homo_sapiens/variation/meta.txt, t/test-genome-DBs/homo_sapiens/variation/table.sql
Three additional variant consequence are being added to the variation test DB
=> Patching variation test db with new consequences

lib/EnsEMBL/REST.pm
Updating the docs: update version and change-log. Only updated minor version since no major bugfixes or changes were …
=> Updating docs to point to latest version 15.2

.travis.yml, README.md
Pushed new branch before committing these changes (by mistake).
Updating the travis and coveralls badges to point to release/107 branch, as well as testing branch in .travis.yml
=> Updating travis and coveralls branches

root/documentation/vep.conf
The VEP endpoint will have the external plugin GO available. This documentation is needed for the plugin.
Documentation check only.
[/vep/:species/hgvs/] new plugin option added: GO
[/vep/:species/id/] new plugin option added: GO
[/vep/:species/region/] new plugin option added: GO
=> New VEP plugin GO

root/documentation/vep.conf
Same as #530 but against release/107
=> Add docs for VEP GO plugin for 107

lib/EnsEMBL/REST.pm
Update REST version and Update docs pointer to latest version (REST version 15.4, for Release 109). Refers to task A5 in …
=> Update REST version and update docs pointer for release 109

root/documentation/vep.conf
[ENSVAR-2852](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-2852): Documentation for new Geno2MP plugin for VEP REST
Check documentation update in my [sandbox](http://wp-np2-11.ebi.ac.uk:9301/documentation/info/vep_hgvs_get).
Link to plugin will not work because Geno2MP was still not merged: https://github.com/Ensembl/VEP_plugins/pull/580
Documentation for Geno2MP plugin
[/vep] Added Geno2MP plugin
=> Document Geno2MP plugin for VEP REST (110)

root/documentation/vep.conf
[ENSVAR-5917](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5917)
Possible Drawbacks
No drawbacks.
Testing
Changes to documentation can be checked in http://wp-np2-11.ebi.ac.uk:7075/documentation/info/vep_region_get
Changelog
[/vep] Documented Enformer plugin
=> Adding changes for Enformer

lib/EnsEMBL/REST.pm
- Update docs pointer for Release 112
- Update REST version to 15.8 in perl module file.
=> Update docs pointer to latest version (release/112)

lib/EnsEMBL/REST.pm
- Update docs pointer for Release 112
- Update REST version to 15.8 in perl module file.
=> Update docs pointer to latest version (main)

root/documentation/vep.conf
Sister PR of - https://github.com/Ensembl/ensembl-rest/pull/618
=> Add new plugin DosageSensitivity

lib/EnsEMBL/REST/Controller/VEP.pm, root/documentation/vep.conf
Sister PR of - https://github.com/Ensembl/ensembl-rest/pull/619
=> Improve CADD: add SV and pig CADD support (e112)

root/documentation/vep.conf
[ENSVAR-6046](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6046): Document new VEP plugin [RiboseqORFs](https://github.com/Ensembl/VEP_plugins/pull/690)
See documentation changes in http://hl-codon-25-01.ebi.ac.uk:3000
[/vep] Add plugin RiboseqORFs
=> Add VEP plugin RiboseqORFs (e113)

.travis.yml, t/test-genome-DBs/ancestral_sequences/core/meta.txt, t/test-genome-DBs/ancestral_sequences/core/table.sql, t/test-genome-DBs/gallus_gallus/core/meta.txt, t/test-genome-DBs/gallus_gallus/core/table.sql, t/test-genome-DBs/homo_sapiens/core/meta.txt, t/test-genome-DBs/homo_sapiens/core/table.sql, t/test-genome-DBs/meleagris_gallopavo/core/meta.txt, t/test-genome-DBs/meleagris_gallopavo/core/table.sql, t/test-genome-DBs/taeniopygia_guttata/core/meta.txt, t/test-genome-DBs/taeniopygia_guttata/core/table.sql
Updates to ensembl-rest repo based on changes brought in for PR https://github.com/Ensembl/ensembl/pull/680.
=> Release 110 - Patch test databases to allow null meta_value and extend the meta_key varchar length

root/documentation/vep.conf
Add AlphaMissense plugin to VEP REST ([ENSVAR-6262](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6262))
Commits cherry-picked from https://github.com/Ensembl/ensembl-rest/pull/632
Check documentation changes in my sandbox: http://hl-codon-36-01.ebi.ac.uk:3000/documentation/info/vep_region_get
[/vep] Added AlphaMissense plugin
=> Add AlphaMissense plugin to VEP REST (main)

ensembl_rest.conf.default
Description
Update out-of-date reg. feature in the documentation page .
=> Out-of-date reg. feature update (112)

root/documentation/vep.conf
[ENSVAR-6172](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6172): add LOEUF plugin to VEP REST
Test documentation changes in [my sandbox](http://hl-codon-08-01.ebi.ac.uk:3000)
[/vep] Add LOEUF plugin to VEP REST
=> Document LOEUF plugin in VEP REST (113)

lib/EnsEMBL/REST.pm
Update the REST version and update the docs pointer.
=> [113] Update docs pointer to latest version

lib/EnsEMBL/REST.pm
Update the REST version and update the docs pointer on the main branch.
=> [114] Update docs pointer to latest version

lib/EnsEMBL/REST/Model/ga4gh/Beacon.pm, root/documentation/vep.conf
Sister PR https://github.com/Ensembl/ensembl-rest/pull/672
=> Deprecate Mastermind plugin

lib/EnsEMBL/REST.pm
Update docs pointer to latest version.
Updated REST version
Updated Changelog 
None
N/A
* `[/vep]` Add Paralogues plugin
* `[/vep]` Update dbNSFP data to 4.9c
* `[/ga4gh/beacon/query]` Beacon does not return DisGeNET scores anymore
* `[/ga4gh/beacon/query]` Beacon does not return Mastermind scores anymore
* `[/vep]` DisGeNET plugin is deprecated
* `[/vep]` Mastermind plugin is deprecated
=> Update docs pointer to latest version
