Ensembl/ensembl-rest

- lib/EnsEMBL/REST/Model/ga4gh/variants.pm
Fix to avoid warn message when query region has no data
> exit earlier if no data

- lib/EnsEMBL/REST/Controller/Assembly.pm
- t/assembly_info.t
Addition of topology information, using is_circular rather than topology for consistency with other endpoints.
> added is_circular attribute for topology of seq_regions

- lib/EnsEMBL/REST/View/TT.pm
This is achieved by adding the username to the path under /tmp. Similar to
bf6bc139 but this time on TT.pm
> Allow mult. users to serve from the same machine

- lib/EnsEMBL/REST/Controller/GeneTree.pm
- lib/EnsEMBL/REST/Controller/Homology.pm
- root/documentation/compara.conf
cf RT #475008
- New option in the gene-tree end-points to output the cigar-lines. Default is False to preserve the current behaviour
- New option in the homology end-points to output the cigar-lines. Default is True to preserve the current behaviour. I would personally prefer the default to be False but it would mean changing the major version number :/
> New option to output the CIGAR line of the alignment

- t/overlap.t
The name give to the allele string in the VariationFeature summary_as_hash method is missleading, so has been updated. This updates the relevant REST test.
> Correct summary_as_hash key

- lib/EnsEMBL/REST/Controller/Sequence.pm
- t/lib/RestHelper.pm
- t/sequences.t
- Allow users to specify start and end coordinates for a sequence when using the /sequence/id endpoint
- Testing for sub-sequence calls
- Added new tests to harness to check return code and do a regex test on the response regardless of return code (ie. text response on a 400)
- Modified tests to use these new test types for start/end coordinates beyond sequence boundaries
> ENSCORESW-1480

- lib/EnsEMBL/REST/Model/Overlap.pm
Use a hash instead of grepping loads, and assign the VF
properly to the TV so it doesn't go and load it again.
Also needs a fix to VariationFeatureOverlap.pm in
ensembl-variation to properly go faster.
> Speed up transcript_variation fetch (copy of master PR)

- lib/EnsEMBL/REST/Model/Overlap.pm
Use a hash instead of grepping loads, and assign the VF
properly to the TV so it doesn't go and load it again.
Also needs a fix to VariationFeatureOverlap.pm in
ensembl-variation to properly go faster.
> Speed up transcript_variation fetch

- ensembl_rest.conf.default
- lib/EnsEMBL/REST/Model/Registry.pm
Object uses an after BUILD modifier to trigger the population of the
registry and associated lookups. Use with a pre-fork server to
avoid nasty running server process startup costs caused by reaping
processes.
> Enabling pre-load of the Registry

- lib/EnsEMBL/REST/Model/LDFeatureContainer.pm
- t/ld.t
This modifier tells the variation API to not fetch VariationFeature objects, but rather rely on the position->ID mapping extracted from the VCF during genotype extraction. This should make these REST calls many times faster (5-8x faster in my tests).
It depends on a set of changes in ensembl-variation master for the speedup, but safely falls back to the old behaviour when using release/83.
> use modifier to speed up LD calls

- .travis.yml
- lib/EnsEMBL/REST/Controller/VEP.pm
- travisci/harness.sh
Changes have been made to the VEP to use Faidx (FASTA indexing from HTSlib) from Bio::DB::HTS rather than its own module. These changes are to accompany this.
Relevant pull requests are:
https://github.com/Ensembl/ensembl-variation/pull/25
https://github.com/Ensembl/ensembl-tools/pull/12
> move to Bio::DB::HTS module from faidx_xs

- Makefile.PL
Affected from 'release/82' branch.
I tried to run on my VM side
vagrant@precise64:~/src/ensembl-rest$ perl script/ensembl_rest_server.pl
(over plack and other ways to run application I got the same result)
You must configure a default store type unless you use exactly one store plugin. at /usr/local/share/perl/5.14.2/Catalyst/Plugin/ConfigLoader.pm line 101.
Compilation failed in require at /usr/local/share/perl/5.14.2/Catalyst/ScriptRunner.pm line 50.
Looks like, application can't find a correct configuration file.
It's caused after using a default configuration file  'ensembl_rest.conf.default' instead of 'ensembl_rest.conf'.
If user want to solve such issue user should create an own configuration file.
I suggest to copy a default configuration file into correct one on build step(Or …
> Copy a default configuration file on build step

- .travis.yml
- travisci/harness.sh
Shared object files no longer copied, PERL5LIB used to locate instead.
> Tidy of TravisCI tests Bio::DB::HTS setup

- root/documentation/gacallset.conf
Search by multiple VariantSetIds removed in v0.6.0a1 but docs not fully updated.
> correct error in GA4GH docs

- root/documentation/gavariant.conf
Use 3 samples to filter 1KG genotypes for quicker rendering.
Requires: https://github.com/Ensembl/ensembl-rest_private/pull/11
> Docs change - filter GA4GH variant calls returned

- root/documentation/info.tt
Currently an error in the endpoint's response will integrate into the page's DOM (creating this odd looking header section).  This commit encodes the response as HTML elements, so it appears in the example output box as HTML code.
>  Encode error text at HTML so it doesn't integrate into the DOM

- root/documentation/examples/curl.tt
- root/documentation/examples/java.tt
- root/documentation/examples/perl.tt
- root/documentation/examples/ruby.tt
For some endpoints species alias that contains space charactter could
appear in the URI path. In some languages and tools, URLs are not
automatically encoded. The space characters in the URLs cause failure
in the requests.
This change escapes space characters in the URLs for the example requests
for Curl, Java, Perl and Ruby, according to this document:
http://template-toolkit.org/docs/manual/Filters.html#section_url
Fixes ENSEMBL-4809.
> Escape space characters in the URLs for example requests

- ensembl_rest.conf.default
- lib/EnsEMBL/REST/Controller/GenomicAlignment.pm
Hi guys, and happy new year !
During e87 @lairdm told me that we're not configuring the path to access HAL files is not great at all (it's a euphemism). I think it's hard-coded at the moment. Instead, the path should be configured in the main configuration file, and the endpoint should tell the API "This is where you'll find the data".
Here I'm adding a parameter to to the configuration file and pass it to the Compara API (there is a matching change on our side).
I'd still like to keep the same directory structure as on the web server, which is /DATA/PATH/multi/hal_files/*.hal (/DATA/PATH is the bit that's changed in ensembl_rest.conf). Would that fit you ?
If that's OK, then you would just have to rsync Web's /DATA/PATH/multi/ with yours and all the file-based data would work on both …
> Path to HAL files

- lib/EnsEMBL/REST/Model/Registry.pm
For most (if not all) of species found in EG's collection databases, "species.strain"
and "species.strain_collection" are not available as the meta_key in meta tables.
Adding these two with others will return no matching rows.
Fix ENSEMBL-4870.
> fix: get strain info from separate query

- root/documentation/compara.conf
This was causing the examples on my test rest server to failed. The input parameters were clearly wrong so all the issues with the last pull request must have led to an untested version of the documentation file being pushed.  
All appear to be fixed now.
> fixed example's input errors in documentation file

- lib/EnsEMBL/REST/Controller/Homology.pm
- lib/EnsEMBL/REST/Model/Registry.pm
In EnsemblGenomes we have vertebrate gene ids stored in compara pan homology
database. These ids are not loaded into stable_id_lookup database. When a user
wants to fetch homologues through a vertebrate gene id, it returns error because
the id is not found in stable_id_lookup database.
This change allows searching compara dbs at homology endpoint so that when a
vertebrate gene id is not found in the stable_id_lookup database, we continue to
search for it in compara dbs, so that the id could be used to fetch homologues
through EnsemblGenomes's rest endpoint.
Related to ENSEMBL-5061.
> Add searching compara dbs for a gene id at homology endpoint

- root/documentation/ld.conf
The endpoint desc had :/ instead of /:
> Correct typo in ld_pairwise_get endpoint value

- t/overlap.t
- t/regulatory.t
Reflect changes in Funcgen Repo, changed ID -> id to match all the other endpoints. …
>  Changed ID -> id to match all the other endpoints.

- t/info.t
The /info/comparas test assumes that the test compara database is in the same version as the test core database. This assumption is not always met (e.g. before branching the API, or when developing locally).
The commit solves the issue by comparing the version returned by the endpoint to the one of the database itself
No more Travis failures
None
Yes.
Pass, of course.
Yes.
> The /info/comparas endpoint returns the version of the compara database, not the core database

- root/documentation/compara.conf
Whilst comparing the e! and EG family endpoints, Matthieu found a couple of minor issues in our documentation:
https://rest.ensembl.org/documentation/info/family_member_id : db_type, object_type and species are not used in this endpoint (they're only used in the member_symbol endpoint)
https://rest.ensembl.org/documentation/info/family : the documentation is missing the member_source option
https://rest.ensembl.org/documentation/info/family_member_id : db_type, object_type and species are not used in this endpoint (they're only used in the member_symbol endpoint)
https://rest.ensembl.org/documentation/info/family : the documentation is missing the member_source option
Clarity
none
N/A
Yes.
N/A
no
> fix family endpoint documentation

- lib/EnsEMBL/REST/Controller/VEP.pm
- t/vep.t
_One or more sentences describing in detail the proposed changes._
For the POST endpoints for hgvs and id vep input, …
> Added format types to POST endpoints

- ensembl_rest_testing.conf
- lib/EnsEMBL/REST/Controller/Info.pm
- lib/EnsEMBL/REST/Model/Biotype.pm
- root/documentation/info.conf
- t/info.t
- t/test-genome-DBs/homo_sapiens/core/biotype.txt
- t/test-genome-DBs/homo_sapiens/funcgen/epigenome.txt
- t/test-genome-DBs/homo_sapiens/funcgen/meta.txt
- t/test-genome-DBs/homo_sapiens/funcgen/table.sql
Added some biotype info endpoints. Namely info/biotypes/groups and info/biotypes/name
Existing info/biotypes remains …
> Biotype endpoints

- lib/EnsEMBL/REST/Model/Phenotype.pm
- t/lookup.t
- t/phenotype_gene.t
- t/test-genome-DBs/homo_sapiens/variation/phenotype_ontology_accession.txt
The phenotype REST endpoint retrieves the existing phenotypes but currently does not report the associated ontology accession terms. This is now being updated. 
The endpoint functionality stays the same. 
The result of the endpoint will now also contain ontology accessions.
None.
Yes. The corresponding tests have been updated. 
Tests pass with release/93 branch code.
Yes.
The endpoint functions as before, just the output is enriched with accession terms if they exist.
> export phenotype ontology accessions

- t/gene_tree.t
- t/genomic_alignment.t
The Compara API has been fixed not to print distances for the root node of trees any more. This commit fixes the tests of this repo.
cf Description
cf Description
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras molestie tincidunt quam, id dapibus mauris consequat eu. Phasellus in neque quis purus laoreet malesuada in sit amet tellus.
Yes.
Pass, of course.
Yes.
No functionality change
> The Compara API doesn't print :0 on the root node any more

- lib/EnsEMBL/REST/Model/Phenotype.pm
Removing the private method call to reflect the bug fix in the dependent repository.
The endpoint functionality stays the same.
The result of the endpoint will contain ontology accessions without the need of calling a private method.
None.
No change in the tests was needed.
Tests pass.
Yes.
The endpoint functionality is not changed.
> remove use of private method

- root/wrapper.tt
New GDPR privacy policy link for archive 89 site.
> Add new privacy policy link for archive 89 site

- root/wrapper.tt
New GDPR privacy policy link for archive 88 site.
> Add new privacy policy link for archive 88 site

- root/wrapper.tt
New GDPR privacy policy link for archive 87 site.
> Add new privacy policy link for archive 87 site

- root/wrapper.tt
New GDPR privacy policy link for archive 91 site.
> Add new privacy policy link for archive 91 site

- lib/EnsEMBL/REST/Controller/Info.pm
- lib/EnsEMBL/REST/Model/Variation.pm
- root/documentation/info.conf
- t/info.t
The variation/population REST endpoint retrieves population names, descriptions and sample counts. Individuals/Population are also of interest. This update allows the retrieval of individual names and any genders for a given population name. 
We have had requests for the ability to retrieve lists of individuals by population to help in analysis of genotype data. This functionality was only available in the perl API.
GET info/variation/populations/:species/:population_name
The update allows retrieval of all individuals for a population from a species.
None.
Yes. The corresponding tests have been updated.
Tests pass.
Yes.
[/info/variation/population] Added the ability to retrieve all …
> update info/variation/population REST endpoint to retrieve individuals

- root/wrapper.tt
New GDPR privacy policy link for archive 90 site.
> Add new privacy policy link for archive 90 site

- lib/Plack/Middleware/EnsThrottle.pm
- t/ratelimit.t
Anonymise the IP addresses used to rate-limit REST API users. A user-agent derived salt is added to the IP address and MD5 is used to encode it. 
Production use of ensembl-rest requires a transient database record of user activity above what is collected at the institution load balancer.
This is a good faith effort to mitigate our obligations w.r.t. GDPR compliance. User IP storage is transient and never in plain text form. We would need to expend great effort to extract the IP addresses from the rate limiter.
A per-request cost to encode the user's IP. Very unlikely hash collision, where two users end up sharing the same rate limit.
A simple cross-check is added that tests the encoded IP address is a hash and not an IP.
This change should be invisible to users.
> [ENSCORESW-2749] Add a hashing algorithm and user-derived salt to rate limiter

- selenium/scripts/check_endpoints.pl
Selenium test script to check that all endpoint documentation examples load without error.
After setting up a REST server, run the script to check that all endpoints appear to be working.
Helps to pick up obviously broken endpoints or missing documentation params. Useful when setting up the staging/test/live servers.
Can't think of any.
n/a
n/a
> Add endpoint checker script

- lib/EnsEMBL/REST.pm
Turns out the commit which was supposed to bump the version, did not. Given there will have been breaking changes between e93 and e94, we'd better make sure the server version number does get updated before the release day.
> Bump version to 8.0, e94 - for real this time

- lib/EnsEMBL/REST/Controller/Sequence.pm
- t/sequences.t
1. Cherry-pick the ENSCORESW2842 fix from master. That was apparently supposed to be done by Mag bug she hasn't managed to take care of it before her holiday.
2. Update the docs pointer to have the above + implementation of the BindingMatrix endpoint (which got cherry-picked earlier) listed in the e94 change log.
> E94 backports

- lib/EnsEMBL/REST/Model/Variation.pm
- t/variation.t
For population allele frequencies only return the allele count if available
Currenty if there is allele_frequency …
> For population allele frequencies only return allele count if available

- bin/production/server_control.pl
Only try to create log/PID dirs if the server is starting.
The server control script may be used for other purposes than starting the server, 
e.g. the REST installer uses the server control script to generate an init script, at which time we should not create these dirs.
The installer works properly
none
Tested in my sandbox
Server log/PID dirs now only created on server start operations
> Only try to create log/PID dirs if the server is starting.

- lib/EnsEMBL/REST/Model/GenomicAlignment.pm
- t/genomic_alignment.t
When an alignment block doesn't match the required `$display_species`, the Compara API returns undef. This causes the REST to fail over undefined values.
http://rest.ensembl.org/alignment/region/taeniopygia_guttata/2:106040000-106040050:1?content-type=application/json;species_set_group=amniotes;method=PECAN;display_species_set=cat;display_species_set=sheep;display_species_set=mus_musculus_casteij
The alignment block will now be discarded. If all blocks are discarded, the REST API will show the usual error message (as JSON) e.g. http://rest.ensembl.org/alignment/region/mus_musculus/1:50-52:1?species_set_group=murinae;content-type=application/json;method=CACTUS_HAL
_Have you added/modified unit tests to test the …
> No alignment available after filtering by "display_species"

- ensembl_rest.conf.default
- root/documentation/vep.conf
Added a 4th example for HGVSp to the vep_hgvs_get endpoint
As requested by Ben on 13th November - A user would like …
> Adds HGVSp example to documentation

- lib/EnsEMBL/REST/Controller/GenomicAlignment.pm
- lib/EnsEMBL/REST/Model/GenomicAlignment.pm
- root/documentation/compara.conf
- t/genomic_alignment.t
Those commits have already been reviewed and accepted on the release/95 branch, see #312 and #313. This PR is to copy them to master
For all the other sections of this template, see the original PRs for more details. There is
1. a fix to handle undefined values when filtering whole-genome alignments
2. a change to allow the real list of whole-genome alignments methods available in the database, rather than an hard-coded list
yes
yes
> Cherry-picked commits from e95

- ensembl_rest.conf.default
- lib/EnsEMBL/REST/Model/Registry.pm
- t/info.t
Default division changed from 'ensembl' to 'EnsemblVertebrates' in line with Ensembl 95 changes to species.division …
> Change default division to be 'EnsemblVertebrates'

- ensembl_rest.conf.default
- root/documentation/variation.conf
- t/variation.t
Update Variant Recoder to accept SPDI format as input and output. 
Allow the users to use SPDI notation. 
Users can input SPDI format and get the corresponding variant identifier, HGVS and SPDI notation. 
None
Added some tests and all passed. 
[variant_recoder/] Also retrieve a SPDI for a given variant identifier, HGVS or SPDI notation.
> Variant Recoder REST updated to accept SPDI format

- t/test-genome-DBs/homo_sapiens/funcgen/meta.txt
- t/test-genome-DBs/homo_sapiens/funcgen/table.sql
This PR should resolve schema inconsistencies of …
> resolve funcgen test db schema inconsistencies

- lib/EnsEMBL/REST/Model/GenomicAlignment.pm
- t/genomic_alignment.t
I forgot to include this commit in #321 :disappointed:
The commit itself has already been reviewed and accepted on the release/95 branch (#312). This PR is to copy it to master before the e96 branch is created.
The change is a fix to handle undefined values when filtering whole-genome alignments
yes
yes
> Missing commit from e95

- lib/EnsEMBL/REST/Controller/GenomicAlignment.pm
- lib/EnsEMBL/REST/Controller/Homology.pm
- lib/EnsEMBL/REST/Model/Lookup.pm
- lib/EnsEMBL/REST/Model/Overlap.pm
- lib/EnsEMBL/REST/Model/Registry.pm
- root/documentation/compara.conf
- root/documentation/info.conf
- t/info.t
- t/test-genome-DBs/ancestral_sequences/core/meta.txt
- t/test-genome-DBs/gallus_gallus/core/meta.txt
- t/test-genome-DBs/homo_sapiens/core/meta.txt
- t/test-genome-DBs/meleagris_gallopavo/core/meta.txt
- t/test-genome-DBs/taeniopygia_guttata/core/meta.txt
The default compara is set to 'vertebrates' …
> ENSCORESW-3015: replace multi with vertebrates for compara usage

- root/documentation/examples/python3.tt
(Second version of #338, against master this time)
Add parentheses to the "print" call in the rest API documentation for Python 3 (in case of plain text result).
Python3 needs parentheses for "print", contrary to Python2. Users copying-pasting the example code are currently getting an syntax error.
No syntax error for users...
None.
No tests changed: only a doc template was modified.
> Python3 print needs parentheses

- root/documentation/vep.conf
Add the existing Phenotypes VEP plugin as an option to the REST VEP endpoint. This is a duplicate of master PR https://github.com/Ensembl/ensembl-rest/pull/344.
This documentation is needed for the plugin to be visible on the REST endpoint page.
Users will be able to retrieve phenotypic information reported by the plugin.
None.
No tests added. Local test server page checked manually.
_Have you …
> add documentation to VEP endpoint for new plugin - e96

- lib/EnsEMBL/REST/Controller/Info.pm
- root/documentation/info.conf
- t/info.t
Revert "remove info/species endpoint, superseded by info/genomes/division endpoint"
This reverts commit b13284c1af6294005e6a68a1787cae0bd6129ac3.
Keep both endpoints for backward compatibility.
As agreed with @magaliruffier
> Reistate info/species endpoint

- lib/EnsEMBL/REST/Controller/Info.pm
- root/documentation/info.conf
- t/info.t
Revert "remove info/species endpoint, superseded by info/genomes/divi…sion endpoint"
This reverts commit b13284c1af6294005e6a68a1787cae0bd6129ac3.
Keep both endpoints for backward compatibility.
As agreed with @magaliruffier
> Reinstate info/species endpoin

- t/regulatory.t
- t/test-genome-DBs/homo_sapiens/funcgen/meta.txt
- t/test-genome-DBs/homo_sapiens/funcgen/table.sql
Changes in the regulatory.t test are done to match the schema changes in the Epigenome table of the funcgen DB. Also, …
> add epigenome schema changes

- .travis.yml
- README.md
This makes travis run coveralls for the most recent (tested) perl version.
Resolves ENSCORESW-3069
coveralls was not …
> Activate coveralls

- root/documentation/variation.conf
Need to change the description of endpoint variant_recoder/ because a new optional field was added 
This documentation is needed to allow users to know it is possible to output VCF format.  
Users may get VCF format as output.  
None 
No tests needed 
The functionality of the endpoint is the same.
> Documentation add optional field in variant_recoder/ 

- t/test-genome-DBs/multi/ontology/table.sql
The last patching of test databases in this repository missed ontology-DB patches because the patcher script has only just been updated to look for said patches in their new home. Make sure test databases are up to date before the release date.
> Test DB: add missing ontology patches

- .travis.yml
Two changes:
- have the cloning of _ensembl-hdf5_ honour the value of $ENSEMBL_BRANCH instead of always using the master branch,
- quote the value of $ENSEMBL_BRANCH to future-proof ourselves against funky branch names and broken shells.
Core release procedures have just been updated so that _ensembl-rest_ Travis builds on release branches use corresponding release branches in other Ensembl repositories instead of master. Right now implementing this required the branch-name changes in two places, and with variable values being unquoted there is potential for getting something wrong.
Release-branch builds of _ensembl-rest_ will only require a change in one place with respect to master to make sure all Ensembl dependencies use the correct release branch, and always quoting the branch name …
> Changes needed to support the use of release branches in Travis builds

- .travis.yml
Make Travis use the _release/97_ branch of dependent Ensembl repositories rather than _master_.
At present Travis builds of ensembl-rest always pull respective master branches even when ensembl-rest itself is on a release branch. This will no longer be the case starting with release 98, and it does make sense to backport the change to release 97 in light of the ongoing issue with failing Variation tests, which will have to be fixed for both _master_ and _release/97_ and which may or may not require changes in _ensembl-variation_ in addition to / rather than _ensembl-rest_.
Travis builds of _ensembl-rest_ for release 97 will no longer pull in master branches of Ensembl repositories, which have already branched to 98 and will diverge more and more from the 97 code base.
None I can think of. …
> Travis [release/97]: use release/97 branch of dependent Ensembl repos

- root/documentation/ld.conf
Documentation update. Correct the maximum allowed region size. We added a check to the code for restricting the maximum allowed region size a long time ago but forgot to update the documentation. This has been reported by a user on the ensembl-dev list.
NA
Correct documentation
None
Not needed
Not needed
------
PR to master is coming shortly
> correction for allowed region size

- cpanfile
- lib/EnsEMBL/REST/Model/Lookup.pm
- t/archive.t
Make sure that the sprintf() call in line 350 of _lib/EnsEMBL/REST/Model/Lookup.pm_ doesn't receive more than the 3 substitution arguments it expects.
Previously said sprintf() call was passed the entire @captures array and at least nowadays that array is longer than 3 elements, resulting in a "redundant arguments" warning which spams the output of the test suite.
Less noise in test output.
None I can think of.
Yes, _archive.t_ - the first test file to have previously produced this warning - now uses _Test::Warnings_. Note that this adds a new test-time dependency to _ensembl-rest_, which however shouldn't be a problem because other Ensembl repositories already depend on _Test::Warnings_.
The test …
> Model::Lookup::find_object_location(): only pass the expected three substitution arguments to sprintf()

- root/documentation/vep.conf
One more VEP plugin will be available through the VEP endpoint. The documentation in this PR is needed for the plugin. The corresponding parameters config are in PR https://github.com/Ensembl/ensembl-rest_private/pull/61
live: http://rest.ensembl.org/documentation/info/vep_id_get
sandbox: http://ves-hx2-76.ebi.ac.uk:6083/documentation/info/vep_id_get
Without this documentation, the endpoint will not display the availability of the functionality in the background.
_If applicable, …
> update endpoint docs - e98

- root/documentation/vep.conf
Copy of PR https://github.com/Ensembl/ensembl-rest/pull/376 (`release/98`) now on `master`
One more VEP plugin will be available through the VEP endpoint. The documentation in this PR is needed for the plugin. The corresponding parameters config are in PR https://github.com/Ensembl/ensembl-rest_private/pull/61
live: http://rest.ensembl.org/documentation/info/vep_id_get
sandbox: http://ves-hx2-76.ebi.ac.uk:6083/documentation/info/vep_id_get
Without this documentation, the endpoint will …
> update endpoint docs

- lib/EnsEMBL/REST/Controller/VEP.pm
- root/documentation/vep.conf
Switches on support for VEPs MANE flag
Adds a flag showing the matching refseq transcript if the related transcript is …
> Add MANE support

- lib/EnsEMBL/REST/Controller/VEP.pm
- root/documentation/vep.conf
- t/vep.t
Add option to display transcript_version for Ensembl transcripts in VEP endpoint results.
Current setup does not report the Ensembl transcript versions, this will still be the default. The new option will allow the transcript version to be reported by using this new option. 
Improved traceability of VEP annotations on specific transcript versions.
None.
Added new test and also tested on local …
> Add transcript_version option for VEP endpoint - e99

- lib/EnsEMBL/REST/Model/Registry.pm
Perl does not propagate readonly through to HDF5, it has now explicitly been added to ensembl-hdf5.
_Describe the …
> Fix for HDF5 issue

- ensembl_rest.conf.default
_The endpoint at http://rest.ensembl.org/documentation/info/regulatory_id returns
{"error":"ENSR00000006733 not found for homo_sapiens"}_
_This PR is to change the example regulation_id to fix that_
_No need to fix manually for future releases_
_Huge :D_
_None_
_The new regulation_id works on the test site at: http://test.rest.ensembl.org/documentation/info/regulatory_id_
> Change the example regulation_id

- root/documentation/vep.conf
Add documentation for the new optional LoF (LOFTEE) plugin in the VEP REST endpoint. The corresponding configuration update is PR Ensembl/ensembl-rest_private#63
Existing plugin functionality will now be available through REST, new LoF.
live: http://rest.ensembl.org/documentation/info/vep_id_get
proposed: http://hx-noah-01-02:3000/documentation/info/vep_id_get
Without this documentation, the endpoint will not display the availability of the functionality in the background.
_If applicable, describe any possible undesirable …
> Add docs for new functionality Loftee plugin option on VEP endpoint - e99

- lib/EnsEMBL/REST/Model/ga4gh/Beacon.pm
- root/documentation/gabeacon.conf
- t/gabeacon.t
Update Beacon endpoint according to the specification: add support to imprecise structural variants (imprecise start and end locations) and an option to search variants in different datasets. 
Beacon specification supports datasets, this update is necessary to support that functionality. 
More options to query variants. 
The output of old queries is different, this may create a few problems for users. 
Updated old tests according the new output. 
Added new tests to make sure new options are available. 
Run all tests and no regression detected. 
Old queries still work however their outputs have some differences. 
New input options to search for variants. The new options affect:
ga4gh/beacon (only output affected)  
ga4gh/beacon/query
> Update Beacon endpoint according to specification

- t/test-genome-DBs/homo_sapiens/variation/meta.txt
- t/test-genome-DBs/homo_sapiens/variation/table.sql
Patch variation_citation table. 
The attrib ids used in table.sql are wrong. They have to be fixed for the right values. 
attrib_ids in variation_citation match attrib_id in attrib table
None 
Yes, no regression detected.
No
> Patch variation_citation table 99 

- lib/EnsEMBL/REST.pm
This is to merge the two version-bumping commits from _release/99_ into _master_.
> Bump documentation and REST API version to 11.2

- lib/EnsEMBL/REST/Controller/Info.pm
- lib/EnsEMBL/REST/Model/Variation.pm
- root/documentation/info.conf
- t/info.t
Add an option to include the consequence ranking for the sequence ontology terms. 
There was a request to add the consequence rank for the SO terms. 
One more option to get more info from the consequence terms. 
None. This change doesn't affect old queries. 
Yes
The tests pass. 
No regression detected. 
No, the functionality is the same there's only one more option. 
/info/variation/consequence_types
> Add option to include SO consequence ranking

- ensembl_rest.conf.default
- ensembl_rest_testing.conf
- lib/EnsEMBL/REST/Controller/GenomicAlignment.pm
- lib/EnsEMBL/REST/Controller/Homology.pm
- lib/EnsEMBL/REST/Model/GenomicAlignment.pm
- root/documentation/compara.conf
- root/documentation/compara_grch37.conf
Updated compara endpoints to support removal of many species and analyses from GRCh37 REST service. This includes moving default values to the conf file (instead of hardcoding in the endpoint) and updating documentation & examples for GRCh37 purposes
> Compara endpoint update for grch37

- root/documentation/overlap.conf
There is a broken documentation link on this endpoint description
https://rest.ensembl.org/documentation/info/overlap_id
"(See list of short set names)" now points to a dead link which is
http://www.ensembl.org/info/genome/variation/data_description.html#variation_sets
Propose change to http://www.ensembl.org/info/genome/variation/species/sets.html
> Fix a broken documentation link of variation

- ensembl_rest.conf.default
- root/documentation/compara_grch37.conf
Corrections in variable ids used for grch37 rest compara documentation
Disabling of compara end-points
Correction made …
> correction in variable ids used for grch37 rest documentation

- root/documentation/compara.conf
- t/test-genome-DBs/multi/compara/method_link.txt
_Jira ticket: [ENSINT-334](https://www.ebi.ac.uk/panda/jira/browse/ENSINT-334)._
_EPO\_LOW\_COVERAGE_ method_link.type has been changed to _EPO\_EXTENDED_ to better reflect what the multiple alignment is. The display_name has been changed to `EPO-Extended` to match this also. 
_EPO_LOW\_COVERAGE_ used to be computed on the more fragmented genomes. Now it is used to extend EPO alignments with additional species, which do not have to be "low coverage". Renaming the method to suggest an extension to the EPO alignment is more accurate, and will reduce confusion among users.
_As above._
_NA_
Tests have not been modified, but test databases have, with the method having been renamed. The unit tests have been run, and the change has not caused any failures or regression.
_NA_
> EPO_LOW_COVERAGE->EPO_EXTENDED rename in compara

- root/documentation/vep.conf
This is the same change as #416 for release 100.
The tests are failing because of branches.
[/vep/:species/hgvs/] new plugin option added: SpliceAI
[/vep/:species/id/] new plugin option added: SpliceAI
[/vep/:species/region/] new plugin option …
> Add new VEP plugin documentation release 100

- lib/EnsEMBL/REST/Controller/VEP.pm
- root/documentation/vep.conf
We're allowing the flags --shift_3prime and --shift_genomic to be used on REST
The idea is to provide a standardised way …
> Add flags shift_3prime and shift_genomic to REST

- root/documentation/vep.conf
This is late patch for the current release 100.
For release 100 we updated the dbNSFP data file to the latest version 4.0a. VEP endpoints can use the file to add additional information for a given variant to the output. Supported fields which can be selected from the file are described in a README file. The readme file link wan't updated to the latest file and now causes confusion on which version of dbNSFP is supported and which fields can be selected.
Users can check the readme file for supported version and fields of the dbNSFP data file
Bugfix
None
I checked all occurrences of the [readme file](https://usf.app.box.com/s/cdws8yx5occ603ccbknwyamz5reapdug) and that link works on an instance running on a farm node:
--[vep_hgvs_get](http://hx-noah-13-02.ebi.ac.uk:3000/documentation/info/vep …
> update dbNSFP readme file to verion 4.0a

- t/test-genome-DBs/homo_sapiens/variation/meta.txt
- t/test-genome-DBs/homo_sapiens/variation/table.sql
Apply e102 patch for variation test databases
Test databases will be on e102 schema.
Tests are passing
> Patch variation databases for e102

- ensembl_rest.conf.default
- root/documentation/info_grch37.conf
For now the `info.conf` is shared between www and Grch37. However, there are some info endpoints that are no longer relevant on Grch37, for example:
http://grch37.rest.ensembl.org/documentation/info/eg_version
http://grch37.rest.ensembl.org/documentation/info/info_divisions
This PR is to remove these endpoints from `info.conf`, and save it as `info_grch37.conf`. They include:
1. eg_version
2. info_genome
3. info_divisions
4. info_genomes_division
5. info_genomes_taxonomy
6. info_genomes_assembly
7. info_genomes_accession
`ensembl_rest.conf.j2` in `ensembl-rest_private` is updated so that www and grch37 pick up the right info conf.
Remove broken endpoints
None
The info_grch37.conf works on my sandbox http://ves-hx2-75:4000/
> Remove some info endpoints on Grch37

- root/documentation/vep.conf
Same as #446 for release/102
[/vep/:species/hgvs/] new plugin option added: DisGeNet
[/vep/:species/id/] new plugin option added: DisGeNet
[/vep/:species/region/] new plugin option added: DisGeNet
> Add new VEP plugin documentation for 102

- root/documentation/vep.conf
[/vep/:species/hgvs/] new plugin option added: DisGeNet
[/vep/:species/id/] new plugin option added: DisGeNet
[/vep/:species/region/] new plugin option added: DisGeNet
> Add new VEP plugin documentation 

- t/variation.t
We changed the output structure of the variant recoder tool. The code update is in ensembl-vep.
Variant recoder takes a given variant identifier as input and translates it to any other identifier which also describes the same variant. Some of the identifiers are variant allele specific. Currently all identifiers are returned together even if they refer to different alleles of the input variant. With the update we report identifiers by variant allele.
The update helps users to only select identifiers for the allele they are interested in.
We are also planning a new web tool for which we want to report results by allele.
It is cleaner to report results by allele.
Users will have written parsers for the current format and need to update their code to match the new structure.
I have modified …
> update tests for new variant recoder return structure

- lib/EnsEMBL/REST/Model/ga4gh/Beacon.pm
- t/gabeacon.t
Update the Ensembl Beacon ID. Same as #457 and #458 
The current Beacon ID is not compatible with the Network specifications. 
To be able to register the Beacon in the Elixir Beacon Network. 
None
The test was updated. 
Test pass
No change in functionality.
> Update beacon id

- cpanfile
The current cpanfile does not install Starman, which is a module required to run REST (https://github.com/Ensembl/ensembl-rest/blob/master/bin/production/server_control.pl#L28)
I think the cpanfile installed Starman when we setup REST 101. But since 2 months ago, we have found an issue of missing Starman when setting up REST covid19 and REST 102
Without Starman, REST server won't start
_NONE_
Manually install Starman using `cpanm Starman` and I can start the server
> Add Starman to the cpanfile

- root/documentation/vep.conf
[/vep/:species/hgvs/] new plugin option added: Mastermind
[/vep/:species/id/] new plugin option added: Mastermind
[/vep/:species/region/] new plugin option added: Mastermind
> Add Mastermind plugin 103

- root/documentation/vep.conf
[/vep/:species/hgvs/] new plugin option added: Mastermind
[/vep/:species/id/] new plugin option added: Mastermind
[/vep/:species/region/] new plugin option added: Mastermind
> Add Mastermind plugin

- lib/EnsEMBL/REST/Model/Assembly.pm
- t/assembly_info.t
Removed getTotalLength method from assembly info, as it is deprecated and replaced with getRefLength
After deprecated methods removal, build fails as we use one deprecated method in Assembly.pm
Correct endpoint work
Not found
No
endpoint assembly_info doesn't have "base_pairs" parameter any more.
> REeplace deprecated method with the correct one

- t/variation.t
Variation test data has been converted to HEX and the test runs successfully again.
NA
NA
Tests ran on travis https://travis-ci.org/github/at7/ensembl-rest/builds/754441684
NA
> add test back after blob to hex-blob conversion

- lib/EnsEMBL/REST/Controller/VariantRecoder.pm
- root/documentation/variation.conf
- t/variation.t
Variant Recoder has two more options available. 
We need to add two options:
- vcf_string (at the moment, it can be switched on using `fields` but it's more correct if `vcf_string` is a separate option)
- var_synonyms (new option to report variation synonyms)
More Variant Recoder options.
None
Yes, tests added to t/variation.t
Tests pass
[variant_recoder/:species/:id] Has the option to return VCF and variation synonyms
> Add options to Variant Recoder

- t/test-genome-DBs/homo_sapiens/variation/meta.txt
- t/test-genome-DBs/homo_sapiens/variation/table.sql
Variation has another schema patch for 105. 
Variation needs to add another schema patch to 105 because the publication.title current length is not enough. 
None
No
No
> Patch variation test db 105 

- t/test-genome-DBs/homology/compara/meta.txt
- t/test-genome-DBs/homology/compara/table.sql
- t/test-genome-DBs/multi/compara/meta.txt
- t/test-genome-DBs/multi/compara/table.sql
Patching Compara test databases following a schema change we have just merged in for e105
`perl ${ENSEMBL_ROOT_DIR}/ensembl-test/scripts/runtests.pl t/` failed at `t/gafeatures.t` and `t/ld.t` but they don't seem to be Compara tests. It was agreed with a more senior colleague to open a pull request.  
No.
> Patched test databases for release 105

- t/test-genome-DBs/homology/compara/meta.txt
- t/test-genome-DBs/homology/compara/table.sql
- t/test-genome-DBs/multi/compara/meta.txt
- t/test-genome-DBs/multi/compara/table.sql
Patching Compara test databases following a schema change we have merged in for e105.
* Requested by B. Walts following a PR on `ensembl-rest/release/105` 
`perl ${ENSEMBL_ROOT_DIR}/ensembl-test/scripts/runtests.pl t/` failed at `t/gafeatures.t`, `t/gavariantannotationset.t` and `t/ld.t` but they don't seem to be Compara tests.
No.
> Compara test databases _b patch for 105

- t/test-genome-DBs/homo_sapiens/funcgen/meta.txt
- t/test-genome-DBs/homo_sapiens/funcgen/table.sql
These changes update Funcgen test database with patches for:
- Schema change for release 106.
-  Add indexes to `peak` and `motif_feature_regulatory_feature` tables.
- Version-bump schema change for 106.
-  New indexes tackle performance issues with bigWig tracks.
Failing tests in `t/archive.t`. They don't seem to be related to changes in this PR. 
Same failing tests were reported in #497, #496.
> Patch funcgen test db for 106 and change introduced during 105

- t/test-genome-DBs/homo_sapiens/variation/meta.txt
- t/test-genome-DBs/homo_sapiens/variation/table.sql
Apply e106 patch for variation test databases
Test databases will be  on e106 schema
The following tests are failing …
> Patch variation database for e106

- cpanfile
Carp::Clan has been used in ReurnErrors.pm since at least 104 but wasn't in cpanfile. It seems something used to pull in that dependency transitively for some other purpose so the problem wsan't seen, but now it doesn't (presumably a 3rd-party change in the dependency tree for a package we use), so that dependency needs to be in cpanfile for the server to start up.
This PR is a prerequisite for the 105 test sites being brought up.
Try to start the server via ansible on release/105, it doesn't start, with an error to sdterr about Carp::Clan being missing.
The server can be deployed working with this configuration, but not without it.
None foreseen.
I have run the ansible deploy for the rest server both with this change and without, using this branch on my own repo, and confirmed the claims …
> Add Carp::Clan requirement to cpanfile

- t/test-genome-DBs/homology/compara/meta.txt
- t/test-genome-DBs/homology/compara/table.sql
- t/test-genome-DBs/multi/compara/meta.txt
- t/test-genome-DBs/multi/compara/table.sql
Compara has included wheat cultivars protein trees in e106 and this has flagged a requirement to increase the column of one of our tables.
This patch has been successfully applied to all Compara production pipelines and databases in e106 without raising any incompatibilities or issues.
No
> Increase gene_tree_root.clusterset_id column length

- .travis.yml
Travis build is broken because of some EnsEMBL repos renamed their "master" branch.
Updating Travis settings to fix it.
See above
Restore Travis CI
Not having Travis CI working anymore
No
N/A
> Added git-ensembl to manage renaming of master branch in repos

- t/test-genome-DBs/homology/compara/meta.txt
- t/test-genome-DBs/homology/compara/table.sql
- t/test-genome-DBs/multi/compara/meta.txt
- t/test-genome-DBs/multi/compara/table.sql
Compara has included wheat cultivars protein trees in e106 and this has flagged a requirement to increase the column of one of our tables.
It is the same of PR 512 to be merged against "master".
On Codon, two tests (2 and 6) from gafeatures.t fail because the value for "updated" and "created" features attributes "2008-04-29 11:17:41" is converted to epoch "1209464261" instead of the expected "1209467861".
We are not changing test data because of Travis automatic build/test.
Also on Codon, there are ld.t tests failing because of ld_vcf (in ensembl-variation repo) segfaulting. This is an issue resolved by https://github.com/Ensembl/ensembl-variation/pull/770
No
> Increase gene_tree_root.clusterset_id column size

- root/documentation/vep.conf
The VEP endpoint will have the external plugin UTRannotator available. This documentation is needed for the plugin.
No regression was detected.
eg. …
> New VEP plugin UTRannotator (e107)

- root/documentation/vep.conf
The VEP endpoint will have the external plugin IntAct available. This documentation is needed for the plugin.
eg. [/xenobiology/orthologs] Added the …
> New VEP plugin IntAct (e107)

- root/documentation/vep.conf
The VEP endpoint uses the external plugin AncestralAllele that is already available in REST. This documentation is needed for the plugin. @dglemos
Documentation of VEP plugin available through REST.
Tested by running [ensembl_rest_server.pl](https://github.com/Ensembl/ensembl-rest/blob/release/105/script/ensembl_rest_server.pl). Documentation shows as expected.
[/vep/:species/hgvs/] plugin option available: AncestralAllele
[/vep/:species/id/] plugin option available: AncestralAllele
[/vep/:species/region/] plugin option available: AncestralAllele
> Add AncestralAllele docs

- root/documentation/vep.conf
The VEP endpoint will have the external plugin EVE available. This documentation is needed for the plugin.
Documentation check only.
eg. [/xenobiology/orthologs] Added the ability to look up orthologs and paralogs from klingons and andorians
[/vep/:species/hgvs/] new plugin option added: EVE
[/vep/:species/id/] new plugin option added: EVE
[/vep/:species/region/] new plugin option added: EVE
> feat: Add VEP Plugin - EVE

- root/documentation/vep.conf
The VEP endpoint will have the external plugin EVE available. This documentation is needed for the plugin.
Same as PR #524
Documentation check only.
eg. [/xenobiology/orthologs] Added the ability to look up orthologs and paralogs from klingons and andorians
[/vep/:species/hgvs/] new plugin option added: EVE
[/vep/:species/id/] new plugin option added: EVE
[/vep/:species/region/] new plugin option added: EVE
> Add EVE plugin

- t/test-genome-DBs/homology/compara/meta.txt
- t/test-genome-DBs/homology/compara/table.sql
- t/test-genome-DBs/multi/compara/meta.txt
- t/test-genome-DBs/multi/compara/table.sql
_In e107 Metazoa compara revealed an issue in that the schema expected entirely `UNIQUE` `stable_id` across all genomes. This cannot be the case because divisions such as Metazoa have external annotations and `UNIQUE` `stable_id` is not enforced, not expected._
_The compara schema and API is too tied in with a `UNIQUE` enforcement and may require a larger change later on. For now, changing the case sensitivity is a passable compromise to get compara through e107. (The conflicting `stable-ids` remain unique when case is taken into account)._
_This small change allows the compara schema and API to remain largely unchanged, whilst allowing through the current e107 dataset._
_There are no consequences, bar the fact that future conflicts may require a larger and more complex change. This is …
> Patch test-dbs for compara case insensitive stable_id schema alteration

- lib/EnsEMBL/REST/Model/Overlap.pm
- root/documentation/overlap.conf
- t/test-genome-DBs/homo_sapiens/funcgen/meta_coord.txt
In Regulation we are removing peaks from the funcgen DB from releas 108. The overlap/ and overlap/region endpoints …
> Remove peak feature from overlap endpoints

- root/documentation/vep.conf
The VEP endpoint will not have the external plugin UTRannotator available.
This PR removes docs added in https://github.com/Ensembl/ensembl-rest/pull/517 
Plugin functionality won't be available through REST.
None
Revert the functionality of: 
[/vep/:species/hgvs/] 
[/vep/:species/id/] …
> Remove VEP plugin UTRannotator

- root/documentation/vep.conf
The VEP endpoint will not have the external plugin UTRannotator available.
This PR removes docs added in https://github.com/Ensembl/ensembl-rest/pull/517
Plugin functionality won't be available through REST.
None
Revert the functionality of:
[/vep/:species/hgvs/]
[/vep/:species/id/] …
> Remove VEP plugin UTRannotator (108)

- root/documentation/vep.conf
We are adding new plugin for VEP. This PR add the documentation for that.
Should only be merged if https://github.com/Ensembl/ensembl-rest_private/pull/119 is merged
Tested on sanbox.
[/vep/:species/hgvs/] new plugin option added: mutfunc
[/vep/:species/id/] new plugin option added: mutfunc
[/vep/:species/region/] new plugin option added: mutfunc
> New VEP plugin mutfunc (e108)

- root/documentation/vep.conf
Removing SpliceRegion VEP plugin from ensembl rest. As Splice region consequences is calculated by VEP by default
[ENSVAR-4922](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4922)
> Removing documentation spliceregion rest

- root/documentation/vep.conf
We are adding new plugin for VEP. This PR add the documentation for that.
This is for **Ensembl release e!109**
Use case
Benefits
Possible Drawbacks
Should only be merged if https://github.com/Ensembl/ensembl-rest_private/pull/124 is merged (have related configuration changes)
Should be merged after  https://github.com/Ensembl/ensembl-rest/pull/546 and https://github.com/Ensembl/ensembl-rest/pull/551 (change the same file - so incorporated those changes to avoid a merge conflict)
Testing
Tested on sanbox.
Changelog
[/vep/:species/hgvs/] new plugin option added: NMD
[/vep/:species/id/] new plugin option added: NMD
[/vep/:species/region/] new plugin option …
> Adding new VEP plugin NMD

- root/documentation/vep.conf
A new plugin was added to VEP_Plugins, UTRAnnotator. This is for Ensembl release e!109
Should be merged after https://github.com/Ensembl/ensembl-rest_private/pull/126 is merged.
None
None
Have you added/modified unit tests to test the changes?
Yes, I updated an old test.
If so, do the tests pass/fail?
Tests pass
Have you run the entire test suite and no regression was detected?
None detected
[/vep/:species/hgvs/] new plugin option added: UTRAnnotator
[/vep/:species/id/] new plugin option added: UTRAnnotator
[/vep/:species/region/] new plugin option added: UTRAnnotator
> feat: add plugin UTRAnnotator to vep.conf (release 109)

- lib/EnsEMBL/REST.pm
- root/documentation/vep.conf
A new plugin was added to VEP_Plugins, UTRAnnotator for Release 109.
Should be merged after https://github.com/Ensembl/ensembl-rest_private/pull/126 is merged.
This PR is sister to #559 
Provide docs for new VEP plugin 
None
Test are successful
[/vep/:species/hgvs/] new plugin option added: UTRAnnotator
[/vep/:species/id/] new plugin option added: UTRAnnotator
[/vep/:species/region/] new plugin option added: UTRAnnotator
> UTRAnnotator VEP plugin

- lib/EnsEMBL/REST/Model/ga4gh/references.pm
- t/gareferences.t
Update the ga4gh references endpoint to return the correct fasta file name and FTP location for GRCh37.
None
Yes
No
[/ga4gh/references] Updated the sourceURI for human GRCh37
> Update ga4gh ftp fasta

- lib/EnsEMBL/REST/Controller/Homology.pm
- t/homology.t
On [line 75 of the Ensembl REST Homology controller module in release/109](https://github.com/Ensembl/ensembl-rest/blob/cf8457163df365ddb9a1a5259183773495da65e6/lib/EnsEMBL/REST/Controller/Homology.pm#L75), there is a method call to $lookup->find_object_location($id), where $id contains the Ensembl gene stable_id for which homologies are sought. The return value of this method call is an array — ($species, $object_type, $db_type) — where $species is the relevant species name. On [the corresponding line in release/108](https://github.com/Ensembl/ensembl-rest/blob/1cd1ae1a54c1de3a7e038f4d6b8813ad7fea7c63/lib/EnsEMBL/REST/Controller/Homology.pm#L74), the variable $species was in parentheses, which had the result that the variable was assigned the first value of the array returned by …
> Fixed invalid species bug when no compara division is specified

- lib/EnsEMBL/REST/Controller/VEP.pm
- root/documentation/vep.conf
Sister PR to #568 . This one for `main`.
[ENSVAR-5227](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5227): The miRNA plugin is being deprecated, as that logic was integrated into VEP via the `--mirna` flag. This PR updates REST to conform to VEP's usage.
Note that in REST, `miRNA` should now be `mirna` (lowercase) to properly enable the argument in VEP.
Example: `/vep/human/id/rs569478349?content-type=application/json&mirna=1`
Updates miRNA usage to reflect changes in VEP.
No drawbacks.
The existing unit tests were run and work as expected. No new unit tests were added (I tried adding a test for miRNA flag in rs569478349).
You can test REST in my sandbox, for instance, [rs569478349](http://wp-np2-11.ebi.ac.uk:9301/vep/human/id/rs569478349?content-type=application/json&mirna=1) should …
> VEP P/U miRNA deprecation

- lib/EnsEMBL/REST/Controller/VEP.pm
- root/documentation/vep.conf
Add option to VEP 'ambiguous_hgvs'
Some users need to use the option ambiguous_hgvs when they input an hgvs on VEP REST. This PR adds the option to VEP.
None
No
[/vep/:species/hgvs/] new option 'ambiguous_hgvs' available
> Add option ambiguous_hgvs to vep hgvs endpoint

- lib/EnsEMBL/REST/Controller/VEP.pm
- lib/EnsEMBL/REST/Controller/VariantRecoder.pm
- root/documentation/variation.conf
- root/documentation/vep.conf
[ENSVAR-5274](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5274): Adds support to output the [GA4GH Variation Representation Specification (VRS)](https://vrs.ga4gh.org) standard in VEP and VR.
Requires https://github.com/Ensembl/ensembl-vep/pull/1311
No drawbacks.
Check that `ga4gh_vrs` is returned when enabling the `ga4gh_vrs` flag:
- VEP: http://wp-np2-11.ebi.ac.uk:9303/vep/human/id/rs1210229297?content-type=application/json&ga4gh_vrs=1
- VR: http://wp-np2-11.ebi.ac.uk:9303/variant_recoder/human/rs1210229297?content-type=application/json&ga4gh_vrs=1
[/vep]: Allow to output the GA4GH Variation Representation Specification (VRS) standard
[/variant_recoder]: Allow to output the GA4GH Variation Representation Specification (VRS) standard
> Add support for `--ga4gh_vrs` flag in VEP and VR (110)

- root/documentation/vep.conf
Clarify usage of `ALL` keyword in the documentation of dbNSFP plugin, based on #544. Also added line break tag (`wbr`) to default list in order to visually improve the table layout.
No drawbacks.
Check changes in my [sandbox](http://wp-np2-11.ebi.ac.uk:9304/documentation/info/vep_id_get).
[/vep] Mention `ALL` keyword in documentation of dbNSFP plugin for VEP
> Mention ALL keyword in dbNSFP plugin docs (110)

- lib/EnsEMBL/REST/Controller/VEP.pm
- lib/EnsEMBL/REST/Controller/VariantRecoder.pm
- root/documentation/variation.conf
- root/documentation/vep.conf
[ENSVAR-5301](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5301) – this PR intends to:
- Disable VEP/VR flags in REST we don't want users to access
- Document VEP/VR REST flags with no documentation
- Add and document `--ambiguous_hgvs` as a valid VEP flag
Avoid users using undocumented flags. We decided which flags should be documented and which should be unavailable to users via the REST interface.
Proper documentation to all valid VEP/VR flags in REST.
None.
Mostly changes to docs. Changes to valid flags for VEP/VR should not affect unit tests.
Test in my [sandbox](http://wp-np2-11.ebi.ac.uk:9300).
[vep/] Documented all valid flags in VEP REST
[variant_recoder/] Documented all valid flags in VR REST
> Update flags and documentation of VEP and VR REST (110)

- lib/EnsEMBL/REST/Controller/Homology.pm
- t/homology.t
This change reverts method `fetch_by_ensembl_gene` to its `release/108` version, and in doing that restores the ability to query the `homology/id/:id` endpoint by versioned gene stable ID.
Until Ensembl 108, queries of the `homology/id` REST endpoint would return a result for a versioned gene stable ID, even if the initial stable_id_lookup failed, because of a fallback query of Compara databases to verify that the gene could indeed be accessed by the given versioned gene stable ID. As part of the process of deprecating Compara method `MemberAdaptor::fetch_by_stable_id`, that fallback query was removed, which effectively removed support for querying homologies by versioned gene stable ID.
For example, these queries return equivalent results via the Ensembl 108 REST API:
- …
> Revert fetch_by_ensembl_gene to release/108 version

- root/documentation/vep.conf
@diegomscoelho 
Document the usage of an option to match Ensembl transcripts (`transcript_match`) in dbNSFP VEP plugin.
None.
The documentation update can be checked in my sandbox: http://wp-np2-11.ebi.ac.uk:9300/documentation/info/vep_hgvs_get
Also, the parameter is working as described, returning only dbNSFP fields related with the matched Ensembl transcript
- With `transcript_match=1`:  http://wp-np2-11.ebi.ac.uk:9300/vep/human/id/rs867018739?content-type=application/json&dbNSFP=MVP_score,some_invalid_dbNSFP_field,transcript_match=1,Ensembl_transcriptid
- Without `transcript_match`: http://wp-np2-11.ebi.ac.uk:9300/vep/human/id/rs867018739?content-type=application/json&dbNSFP=MVP_score,some_invalid_dbNSFP_field,Ensembl_transcriptid
/vep Documented use of `transcript_match` option for …
> Document `transcript_match` option for dbNSFP VEP plugin (e110)

- t/info.t
@dglemos 
Fix unit test for obtaining VEP consequence rank (recently changed in https://github.com/Ensembl/ensembl-variation/pull/946)
Tests now passing for e110 when run locally
> Fix unit test for VEP consequence rank (110)

- lib/EnsEMBL/REST.pm
Update docs pointer to latest version (REST version 15.6, for Release 110). Refers to task A5 in the Infrastructure …
> Update docs pointer to latest REST version (Release 110)

- lib/EnsEMBL/REST/Controller/Homology.pm
- lib/EnsEMBL/REST/Model/DatabaseIDLookup.pm
- lib/EnsEMBL/REST/Model/Lookup.pm
- lib/EnsEMBL/REST/Model/Registry.pm
- t/homology.t
[Ensembl REST PR #583](https://github.com/Ensembl/ensembl-rest/pull/583) deprecated Compara REST endpoints supporting queries by gene/sequence object stable ID, and introduced replacement endpoints supporting queries by species name and object stable ID. (See [ENSINT-1416](https://www.ebi.ac.uk/panda/jira/browse/ENSINT-1416) for more info.)
One of the potential drawbacks highlighted in PR #583 was the fact that the code being used to fetch all objects matching a given stable ID depended on the presence of a `stable_ids` database. This has been realised in the case of the Ensembl REST staging server: in the absence of a `stable_ids` database, stable ID lookup fails for many of the deprecated/replacement Compara endpoints.
This PR allows the recently deprecated Compara endpoints to function …
> Add long-lookup functionality to Compara endpoints

- ensembl_rest.conf.default
Minor changes to the `ensembl_rest.conf.default` default config file
Update outdated Ensembl version 88 and amended outdated (and non-working) `mysql.ebi.ac.uk`
Reduced annoyance on my side
Complaints from the wistful ones
Successfully performed (manually)
N/A
> updated default config file

- root/documentation/vep.conf
[ENSVAR-5485](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5485): Add documentation for the MaveDB plugin.
No drawbacks.
Changes to documentation can be checked in http://hl-codon-06-01:3000/documentation/info/vep_region_get
[/vep] Documented MaveDB plugin
> Document MaveDB plugin in VEP (110)

- lib/EnsEMBL/REST/Model/ga4gh/Beacon.pm
Update Beacon endpoint to run VEP.
The idea is to return output for the following:
-  IntAct
-  Mastermind
- GO
- Phenotypes
- DisGeNET
- EVE
- SpliceAI
-  frequency data from gnomAD
The Beacon schema does not specify all types of data we want to return so in this PR we return data for the following:
- IntAct
- GO
- Phenotypes
- DisGeNET
- CADD
- frequency data from gnomAD
This change should also be included in release 110.
Some results are not included in the Beacon schema yet (example: pathogenicityPredictions). I created a ticket in the Beacon repo for that: https://github.com/ga4gh-beacon/beacon-v2/issues/76
Return vep data through Beacon, this way users can integrate VEP in Beacon.
None
changes in other repos …
> Improve Beacon v2 (e111)

- root/documentation/vep.conf
[ENSVAR-5485](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5485): Add documentation for the MaveDB plugin.
No drawbacks.
Changes to documentation can be checked in http://hl-codon-06-01:3000/documentation/info/vep_region_get
[/vep] Documented MaveDB plugin
> Document MaveDB plugin (111)

- root/documentation/vep.conf
[ENSVAR-5840](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5840): Add documentation for the new VEP plugin OpenTargets (configured in https://github.com/Ensembl/ensembl-rest_private/pull/134).
Also, update links pointing to VEP_plugin github repo: branch is now `main`.
No drawbacks.
Changes in documentation can be tested in http://hl-codon-21-03.ebi.ac.uk:3000
[/vep] Documented OpenTargets plugin
> Document OpenTargets plugin (e111)

- lib/EnsEMBL/REST.pm
Update docs pointer to latest version (REST version 15.7, for Release 111). Refers to task A5 in the Infrastructure …
> Update docs pointer to latest REST version (Release 111)

- README.md
Updating Travis and Coveralls badges to use the `main` branch, rather than the out-of-date `master` branch.
N/A
Update badges
None
N/A
N/A
> Update travis and coveralls badges to use main branch

- lib/EnsEMBL/REST/Model/Overlap.pm
Sister to PR #612 - this applied to main branch 
Fix issue #588 
Exons of length 1 at the boundary of the given region were not returned by the /overlap endpoint.
Return the exons of length 1 sitting at the region boundary. 
Downstream pipelines can be affected.
Test suite runs fine
N/A
> Include exons of length 1 at the boundary

- ensembl_rest.conf.default
- lib/EnsEMBL/REST/Model/Variation.pm
- root/documentation/variation.conf
- root/documentation/vep.conf
- t/variation.t
- t/vep.t
[ENSVAR-5793](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5793): Return structural variants (SVs) by their ID when using Variation/VEP endpoints.
The information displayed for SVs is based on their Ensembl Variation page: for instance, [esv1815690](https://www.ensembl.org/Homo_sapiens/StructuralVariation/Mappings?db=core;sv=esv1815690)
Requires https://github.com/Ensembl/ensembl-variation/pull/1029.
Users request that these endpoints return SVs (e.g., `esv1815690`). Currently, they only return non-SVs (e.g., `rs699`).
If all IDs are non-SVs, the code will take the same time as before; otherwise, the code looks for the mismatched IDs in the SV table.
Also, some SVs may hit the memory limit, such as in the case of `nsv3901821`, and return an error message: `ERROR: Cannot allocate …
> Return structural variants by ID in Variation/VEP endpoints

- t/test-genome-DBs/homo_sapiens/funcgen/meta.txt
- t/test-genome-DBs/homo_sapiens/funcgen/table.sql
PR to incorporate updates to test databases before branching for Release 112.
Patch relates to `funcgen` data: setting `data_file_id` to `NOT NULL` and enabling auto increment.
Build is now passing.
Up-to-date test databases.
eg. [/xenobiology/orthologs] Added the ability to look up …
> Patch test databases for Release 112 (round 2 before branching)

- root/documentation/vep.conf
Added documentation for new VEP plugin.
Provide information to user about new option available in `vep` rest endpoint.
No drawbacks.
Checked in sandbox - http://wp-np2-11.ebi.ac.uk:7075
[/vep/:species/hgvs/] new plugin option added: DosageSensitivity
[/vep/:species/id/] new plugin option added: DosageSensitivity
[/vep/:species/region/] new plugin option added: DosageSensitivity
> New plugin: DosageSensitivity (e112)

- lib/EnsEMBL/REST/Controller/VEP.pm
- root/documentation/vep.conf
- ADD options to allow CADD-SV and pCADD annotation using CADD option in Ensembl VEP rest endpoints.
- Update docs to reflect these change. 
User trying to annotate CADD for structural variant input for human or SNV for pig
New feature
N/A
Tested in sandbox; see
https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5782
https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6099
[/vep/:species/hgvs/] new option values allowed for: CADD
[/vep/:species/id/] new option values allowed for: CADD
[/vep/:species/region/] new option values allowed for: CADD
> Improve CADD: add SV and pig CADD support (e112)

- ensembl_rest.conf.default
- ensembl_rest_testing.conf
Duplicate of https://github.com/Ensembl/ensembl-rest/pull/624 to be merged with `main` branch
Update dbNSFP README URL to point to information on version 4.5c ([ENSVAR-6120](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6120)).
Required with the updated dbNSFP 4.5c data.
No drawbacks.
[/vep] Update README URL for dbNSFP 4.5c
> Update to dbNSFP 4.5c (main)

- root/documentation/vep.conf
Add AlphaMissense plugin to VEP REST ([ENSVAR-6262](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6262))
Check documentation changes in my sandbox: http://hl-codon-36-01.ebi.ac.uk:3000/documentation/info/vep_region_get
[/vep] Added AlphaMissense plugin
> Add AlphaMissense plugin to VEP REST (e112)

- root/documentation/examples/perl.tt
When printing out non-JSON content with perl, the example REST documentation is currently suggesting to use the response status and reason attributes. This PR updates the perl example to print out the response content instead.
> Perl documentation fix

- ensembl_rest.conf.default
- ensembl_rest_testing.conf
[ENSVAR-6245](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6245): Update dbNSFP README URL to 4.7c data
@dglemos 
[/vep] Update dbNSFP data to 4.7c
> VEP plugins: Update to dbNSFP 4.7c data (e113)

- lib/EnsEMBL/REST/Model/ga4gh/Beacon.pm
Release 113
Update the Beacon response:
- fix gene ontology output
- remove `allele` from the frequency output
The gene ontology is not returning any data because the plugin output format was updated.
To include missing data in the output.
None
No
No regression detected
[/ga4gh/beacon/query] Update output format
> Update Beacon response format

- t/overlap.t
Update the regulatory feature summary response.
Same as #645 - needed because of Travis issue.
Updated test as per #648 - this PR is for `release/113` branch, instead of `main`
> Update regulatory overlap test to reflect the most updated reg. summary [release/113]

- lib/EnsEMBL/REST/Controller/VEP.pm
- root/documentation/variation.conf
- root/documentation/vep.conf
Support gencode_primary flag for VEP REST
VEP and variation endpoints can now discover GENCODE Primary transcripts 
`curl 'http://wp-np2-25.ebi.ac.uk:3000/vep/human/id/rs699?gencode_primary=1' -H 'Content-type:application/json'`
https://github.com/Ensembl/ensembl-vep/pull/1699
Additional flag `gencode_primary` in VEP/variation endpoints
> Support gencode_primary for VEP REST (main)

- root/documentation/vep.conf
Document VEP plugins REVEL and ClinPred
[ENSVAR-6395](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6395): add ClinPred plugin to web VEP + REST
[ENSVAR-6396](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6396): add REVEL plugin to web VEP + REST
Check documentation changes in http://hl-codon-09-02.ebi.ac.uk:3000
[/vep] Added VEP plugins REVEL and ClinPred
> Document VEP plugins REVEL and ClinPred (main)

- root/documentation/vep.conf
Document VEP plugins REVEL and ClinPred
[ENSVAR-6395](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6395): add ClinPred plugin to web VEP + REST
[ENSVAR-6396](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6396): add REVEL plugin to web VEP + REST
Check documentation changes in http://hl-codon-09-02.ebi.ac.uk:3000
[/vep] Added VEP plugins REVEL and ClinPred
> Document VEP plugins REVEL and ClinPred (e113)

- lib/EnsEMBL/REST/Controller/VEP.pm
- root/documentation/variation.conf
- root/documentation/vep.conf
Support gencode_primary flag for VEP REST
VEP and variation endpoints can now discover GENCODE Primary transcripts 
`curl 'http://wp-np2-25.ebi.ac.uk:3000/vep/human/id/rs699?gencode_primary=1' -H 'Content-type:application/json'`
https://github.com/Ensembl/ensembl-vep/pull/1699
Additional flag `gencode_primary` in VEP/variation endpoints
> Support VEP Gencode primary for REST (e113)

- root/documentation/compara.conf
This PR adds `CACTUS_DB` (Cactus alignment via database) to the list of genomic alignment methods in the documentation. …
> Add CACTUS_DB to the list of genomic alignment methods

- root/documentation/compara.conf
This PR adds `CACTUS_DB` (Cactus alignment via database) to the list of genomic alignment methods in the documentation. …
> Add CACTUS_DB to genomic alignment method list

- lib/EnsEMBL/REST/Model/Overlap.pm
- t/overlap.t
Ensembl Widget compatibility changes:
- Revert regulatory summary function (`summary_as_hash`);
- Filter EMARs reg. features;
payload:
```bash
{
"strand": 0,
"seq_region_name": "7",
"source": "Ensembl",
"extended_end": 140624542,
"start": 140624521,
"id": "ENSR7_53843KH",
"description": "CTCF_binding_site",
"feature_type": "regulatory",
"end": 140624542,
"extended_start": 140624521
}
```
reverted to:
```bash
{
"seq_region_name": "7",
"source": "Regulatory_Build",
"description": "CTCF binding site",
"bound_start": 140624521,
"strand": 0,
"feature_type": "regulatory",
"id": "ENSR7_53843KH",
"start": 140624521,
"bound_end": 140624542,
"end": 140624542
}
```
> Revert regulatory summary and filter EMARs

- root/documentation/vep.conf
[ENSVAR-6290](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6290): Document Paralogues plugin from VEP
@likhitha-surapaneni 
Documents new VEP plugin
You can check the documentation changes in my sandbox: http://hl-codon-36-03.ebi.ac.uk:3000
[/vep] Add Paralogues plugin
> VEP: add Paralogues plugin (e114)

- ensembl_rest.conf.default
- ensembl_rest_testing.conf
[ENSVAR-6368](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6368): Update dbNSFP README URL to 4.9c
Updates URL of README file for dbNSFP on VEP endpoint documentation
@dglemos
[/vep] Update dbNSFP data to 4.9c
> VEP: Update dbNSFP README URL to 4.9c (e114)

- lib/EnsEMBL/REST/Model/ga4gh/Beacon.pm
- root/documentation/vep.conf
This is an update for release 114
Deprecating the VEP plugin: DisGeNET
The DisGeNET data is not freely available anymore.
The plugin does not make sense without the data.
Users won't be able to run the plugin in the future.
no regression detected
[/vep] DisGeNET plugin is deprecated
[/ga4gh/beacon/query] Beacon does not return DisGeNET scores anymore
> Deprecate DisGeNET (release 114)

- lib/EnsEMBL/REST.pm
- lib/EnsEMBL/REST/Model/ga4gh/Beacon.pm
- root/documentation/vep.conf
Same as https://github.com/Ensembl/ensembl-rest/pull/670
**Description**
Deprecating the VEP plugin: DisGeNET
**Use case**
The DisGeNET data is not freely available anymore.
The plugin does not make sense without the data.
**Benefits**
**Possible Drawbacks**
Users won't be able to run the plugin in the future.
**Testing**
Have you added/modified unit tests to test the changes?
If so, do the tests pass/fail?
Have you run the entire test suite and no regression was detected?
no regression detected
**Changelog**
[/vep] DisGeNET plugin is deprecated
[/ga4gh/beacon/query] Beacon does not return DisGeNET scores anymore
> Deprecate plugin 114

- lib/EnsEMBL/REST/Model/ga4gh/Beacon.pm
- root/documentation/vep.conf
Deprecating the VEP plugin: Mastermind. [ENSVAR-6664](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6664)
Some part of the Mastermind data is not freely available anymore.
Users won't be able to run the plugin in the future.
N/A
[/vep] Mastermind plugin is deprecated
[/ga4gh/beacon/query] Beacon does not return Mastermind scores anymore
> Deprecate Mastermind plugin

- lib/EnsEMBL/REST.pm
Sister to PR #682 
Update docs pointer to latest version.
Updated REST version
Updated Changelog 
None
N/A
* `[/vep]` Add Paralogues plugin
* `[/vep]` Update dbNSFP data to 4.9c
* `[/ga4gh/beacon/query]` Beacon does not return DisGeNET scores anymore
* `[/ga4gh/beacon/query]` Beacon does not return Mastermind scores anymore
* `[/vep]` DisGeNET plugin is deprecated
* `[/vep]` Mastermind plugin is deprecated
> Changes for release 114/61 - updated version and docs

- root/documentation/compara.conf
This PR would update the list of `nh_format` modes of gene-tree REST endpoints:
- https://rest.ensembl.org/documentation/info/genetree
- https://rest.ensembl.org/documentation/info/genetree_species_member_id
- https://rest.ensembl.org/documentation/info/genetree_member_symbol
In particular, it would:
- add new `nh_format` modes `genome_gene_stable_id` and `genome_product_stable_id`;
- add existing format mode `gene_stable_id`; and
- remove unsupported format mode `njtree`.
Examples:
- gene-tree request for NH tree in `gene_stable_id` mode: https://rest.ensembl.org/genetree/id/ENSGT00390000003602?content-type=text/x-nh;nh_format=gene_stable_id
- gene-tree request for NH tree in `njtree` mode: https://rest.ensembl.org/genetree/id/ENSGT00390000003602?content-type=text/x-nh;nh_format=njtree …
> Update NH gene-tree format modes

- lib/EnsEMBL/REST/Model/Overlap.pm
EMAR reg. features are excluded from REST. 
This fix identifies these features by checking if the description is `undef`.
> [115] Fix EMARs exclusions (release/115)
